version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mysql
      - DB_USER=${DB_USER:-notes_user}
      - DB_PASSWORD=${DB_PASSWORD:-notes_password}
      - DB_NAME=${DB_NAME:-notes_db}
      - DB_PORT=3306
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-here}
      - PORT=8000
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_password}
      MYSQL_DATABASE: ${DB_NAME:-notes_db}
      MYSQL_USER: ${DB_USER:-notes_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-notes_password}
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD:-root_password}"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
